# Generated by Django 5.2.6 on 2025-10-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternative',
            options={'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AlterField(
            model_name='alternative',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Is Correct'),
        ),
    ]
