# Generated by Django 5.2.6 on 2025-10-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='order',
            field=models.PositiveIntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], default=1, verbose_name='Order'),
            preserve_default=False,
        ),
    ]
