# Generated by Django 5.2.6 on 2025-10-17 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0002_initial'),
        ('question', '0002_alter_objectivequestion_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='question.objectivequestion'),
        ),
    ]
