# Generated by Django 5.2.6 on 2025-11-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternative', '0002_alternative_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternative',
            options={'ordering': ['order'], 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
    ]
