# Generated by Django 5.2.6 on 2025-11-01 17:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('(^[a-zA-ZÀ-ú ]+$)', 'Invalid name, use just letters')], verbose_name='Name')),
                ('personal_email', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('(^[\\w.%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}$)', 'Invalid email, follow the standart: email@host.extensions')], verbose_name='Personal Email')),
                ('institutional_email', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('(^[\\w.%+-]+@(?!gmail\\.com|hotmail\\.com|outlook\\.com|yahoo\\.com)[\\w.-]+\\.[a-zA-Z]{2,}$)', 'Invalid institutional email, make sure you have spelled it correctly')], verbose_name='Institutional Email')),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('(^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*]).{8,}$)', 'Invalid password. Please ensure you use a password with 8 characters, at least one uppercase letter, at least one lowercase letter, at least one number, and at least one special character')], verbose_name='Password')),
                ('campus', models.CharField(max_length=150, verbose_name='Campus')),
                ('department', models.CharField(max_length=255, verbose_name='Department')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
