# Generated by Django 5.2.6 on 2025-11-22 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator('(^[\\w.%+-]+@[\\w.-]+\\.[a-zA-Z]{2,}$)', 'Invalid email, follow the standart: email@host.extensions')], verbose_name='Personal Email'),
        ),
    ]
