# Generated by Django 5.2.6 on 2025-11-24 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institutional_email',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('(^[\\w.%+-]+@(?!gmail\\.com|hotmail\\.com|outlook\\.com|yahoo\\.com)[\\w.-]+\\.[a-zA-Z]{2,}$)', 'Use um email institucional!')], verbose_name='Institutional Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('(^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*]).{8,}$)', 'Senha incorreta. Verifique se a senha informada segue todos os requisitos de segurança.')], verbose_name='Password'),
        ),
    ]
