# Generated by Django 5.2.6 on 2025-11-24 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_institutional_email_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('(^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[!@#$%^&*]).{8,20}$)', 'Senha incorreta. Verifique se a senha informada segue todos os requisitos de segurança.')], verbose_name='Password'),
        ),
    ]
