# Generated by Django 5.2.6 on 2025-11-02 01:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0002_remove_discipline_subject_remove_discipline_topic'),
        ('question', '0006_question_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('unit', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III')], verbose_name='Unit')),
                ('period', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('(^(19|20)\\d{2}\\.[123]$)', 'Invalid period, make sure that the value is valid')], verbose_name='Period')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Use count')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Topic')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='discipline.discipline', verbose_name='Discipline')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='QuestionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.activity')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
            options={
                'verbose_name': 'Questão de atividade',
                'verbose_name_plural': 'Questões de atividades',
                'unique_together': {('activity', 'order'), ('activity', 'question')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='questions',
            field=models.ManyToManyField(related_name='activities', through='activity.QuestionActivity', to='question.question', verbose_name='Activity questions'),
        ),
    ]
