# Generated by Django 5.2.6 on 2025-11-02 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_created_at_activity_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='period',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('(^(19|20)\\d{2}\\.[123]$)', 'Invalid period, make sure that the value is valid')], verbose_name='Period'),
        ),
    ]
