# Generated by Django 5.2.6 on 2025-11-08 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activity_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionactivity',
            options={'ordering': ['order'], 'verbose_name': 'Questão de atividade', 'verbose_name_plural': 'Questões de atividades'},
        ),
    ]
