# Generated by Django 5.2.6 on 2025-10-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='topic',
        ),
    ]
