# Generated by Django 5.2.6 on 2025-10-08 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('difficulty_level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('D', 'Difficult')], max_length=1, verbose_name='Difficulty level')),
                ('visibility', models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=False, verbose_name='Visibility')),
                ('statement', models.TextField(verbose_name='Statement')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Use count')),
                ('type', models.CharField(choices=[('O', 'Objective'), ('S', 'Subjective')], max_length=1, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('objective', models.CharField(max_length=100, verbose_name='Objective')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='discipline.discipline', verbose_name='Discipline')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Questão Objetiva',
                'verbose_name_plural': 'Questões Objetivas',
            },
        ),
    ]
