# Generated by Django 5.2.6 on 2025-10-11 02:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivequestion',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_questions', to='discipline.discipline', verbose_name='Discipline'),
        ),
        migrations.AlterField(
            model_name='objectivequestion',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='SubjectiveQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('difficulty_level', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('D', 'Difficult')], max_length=1, verbose_name='Difficulty level')),
                ('visibility', models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=False, verbose_name='Visibility')),
                ('statement', models.TextField(verbose_name='Statement')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Use count')),
                ('type', models.CharField(choices=[('O', 'Objective'), ('S', 'Subjective')], max_length=1, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('expected_answer', models.CharField(max_length=500, verbose_name='Expected answer')),
                ('key_answers', models.CharField(max_length=100, verbose_name='Key answers')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_questions', to='discipline.discipline', verbose_name='Discipline')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Questão Subjetiva',
                'verbose_name_plural': 'Questões Subjetivas',
            },
        ),
    ]
