# Generated by Django 5.2.6 on 2025-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.TextField(blank=True, null=True, verbose_name='Subject'),
        ),
    ]
