# Generated by Django 5.2.6 on 2025-10-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_question_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivequestion',
            name='objective',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='key_answers',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Key answers'),
        ),
    ]
