# Generated by Django 5.2.6 on 2025-10-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_objectivequestion_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Topic'),
        ),
    ]
