# Generated by Django 5.2.6 on 2025-11-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectivequestion',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='Objective'),
        ),
    ]
